def section_1_message
    puts ""
    puts ""
    puts "You see a girl at the bar that peaks your interests and gets your testosterone up."
    puts ""
    puts ""
    puts "NEXT?"
    puts "Do you.."
    puts ""
    puts "(1). Make eye contact with her?"
    puts ""
    puts "OR"
    puts ""
    puts "(2). Stare at her body?"
end 

def section_2_message
    puts ""
    puts ""
    puts "You make eye contact with her."
    puts "She looks back at you and smiles."
    puts ""
    puts ""
    puts "NEXT?"
    puts "Do you.."
    puts ""
    puts "(1). Walk towards her with super confidence?."
    puts ""
    puts "OR"
    puts ""
    puts "(2). Smile back at her with super confidence?."
end

def section_3_message
    puts ""
    puts ""
    puts "You approach her so now her attention is focused on you."
    puts ""
    puts ""
    puts "NEXT?"
    puts "Do you ask her.."
    puts ""
    puts "(1). \"What is your name?\""
    puts ""
    puts "OR"
    puts ""
    puts "(2). \"Where is the toilet?\""
end

def section_4_message
    puts ""
    puts ""
    puts "She replies \"What do you want from me? I do not know you!\""
    puts "She’s a bit defensive."
    puts ""
    puts ""
    puts "NEXT?"
    puts "Do you.."
    puts ""
    puts ""
    puts "(1). Introduce yourself?"
    puts ""
    puts "OR"
    puts ""
    puts "(2). Buy her a drink?"
end

def section_5_message
        puts ""
        puts ""
        puts "She replies back my name is Jane with a superfriendly smile on her face."
        puts "She’s opened up, now's the perfect time to approach her closely!" #and assert your dominance as a male."
        puts ""
        puts ""
        puts "NEXT?"
        puts "Do you.."
        puts ""
        puts "(1). Touch her shoulder?"
        puts ""
        puts "OR"
        puts ""
        puts "(2). Touch her leg?"
end

def section_6_message
    puts ""
    puts ""
    puts "You touch her leg and she looks surprised but intrigued."
    puts "She replies, your hand is nice and strong"
    puts ""
    puts ""
    puts "NEXT?"
    puts "Do you ask her.."
    puts ""
    puts "(1). What her mother's name is?"
    puts ""
    puts "OR"
    puts ""
    puts "(2). If you can borrow $10 for an uber ride home."
    puts ""
    puts "OR"
    puts ""
    puts "(3). How many boyfriends she's had before?"
end

def section_7_message
    system "clear"
    puts ""
    puts "CONGRATUALATIONS YOU WIN!"
    puts "Don't actually try this for obvious reasons."
    puts ""
    puts ""
    puts "I am an Uber driver. Give me $10 and I'll drive you home."
    puts ""
    puts ""
    puts "Would you like to play again?"
    puts "To replay (1)"
    puts "To quit (2)"
end
